"""initial_migration

Revision ID: f1e4394d3b31
Revises: 1104461a6506
Create Date: 2023-11-09 15:33:39.289264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e4394d3b31'
down_revision = '1104461a6506'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
